set(_CATKIN_CURRENT_PACKAGE "green_pick")
set(green_pick_VERSION "0.0.0")
set(green_pick_MAINTAINER "lutkus <lutkus@todo.todo>")
set(green_pick_PACKAGE_FORMAT "2")
set(green_pick_BUILD_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs" "cv_bridge" "image_transport" "message_generation")
set(green_pick_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs" "cv_bridge" "image_transport")
set(green_pick_BUILDTOOL_DEPENDS "catkin")
set(green_pick_BUILDTOOL_EXPORT_DEPENDS )
set(green_pick_EXEC_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs" "cv_bridge" "image_transport" "message_runtime")
set(green_pick_RUN_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs" "cv_bridge" "image_transport" "message_runtime")
set(green_pick_TEST_DEPENDS )
set(green_pick_DOC_DEPENDS )
set(green_pick_URL_WEBSITE "")
set(green_pick_URL_BUGTRACKER "")
set(green_pick_URL_REPOSITORY "")
set(green_pick_DEPRECATED "")